[package]
name = "bparse"
version = "0.3.0"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "A library for parsing bytes"
repository = "https://gitlab.com/wake-sleeper/bparse"
keywords = ["parser", "bytes"]


[dependencies]
