[package]
name = "bparse"
version = "0.14.0"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "A library for parsing bytes"
repository = "https://github.com/eze-works/bparse"
keywords = ["parser", "bytes"]

[dependencies]
