[package]
name = "bparse"
version = "0.13.0"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "A library for parsing bytes"
repository = "https://git.sr.ht/~eanyanwu/bparse"
keywords = ["parser", "bytes"]


[dependencies]
